name: Tour_and_Tourism_Management_SE3040 CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  USER: ${{secrets.USER}}
  PASSWORD: ${{secrets.PASSWORD}}
  BACKEND: ${{secrets.BACKEND}}
  FRONTEND: ${{secrets.FRONTEND}}
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: clay-cluster-1
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: github-actions-gke-deployment
  IMAGE: github-actions-gke-image
  TAG: 1.0.0 

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: | # Login to Dockerhub 
        docker login -u $USER -p $PASSWORD
    - name: Build backend docker image
      run: |
        cd backend
        docker build . --file Dockerfile --tag $USER/$BACKEND
    - name: Push user service docker image
      run: docker push $USER/$BACKEND
  
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: | # Login to Dockerhub 
        docker login -u $USER -p $PASSWORD
    - name: Build frontend docker image
      run: |
        cd frontend
        docker build . --file Dockerfile --tag $USER/$FRONTEND
    - name: Push auth service docker image
      run: docker push $USER/$FRONTEND

  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🛠 Configure Kubernetes Credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{secrets.GKE_SA_KEY}}
        project_id: ${{secrets.GKE_PROJECT}}
    - name: ⬆️ Deploy to K8s
      run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
           